CREATE TABLE dtc (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  dtc TEXT NOT NULL,
  description TEXT NOT NULL,
  probable_cause TEXT,
  vinmake_id INTEGER
    REFERENCES vinmake(id) ON DELETE CASCADE
)